# Generated by Django 5.2 on 2025-08-25 16:18

import core.apps.accounts.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.apps.accounts.manager.UserManager()),
            ],
        ),
    ]
