# Generated by Django 5.2 on 2025-08-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_passport_id_user_pnfl_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passport_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pnfl',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
