networks:
  avto_cargo:
    driver: bridge

  
volumes:
  pd_data: null

services:
  nginx:
    networks:
      - avto_cargo
    ports:
      - ${PORT:-8001}:80
    volumes:
      - ./resources/layout/nginx.conf/:/etc/nginx/nginx.conf
      - ./resources/:/usr/share/nginx/html/resources/
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nginx
    depends_on:
      - web
  
  web:
    networks:
      - avto_cargo
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.web
    command: ${COMMAND:-sh ./resources/scripts/entrypoint.sh}
    environment:
      - PYTHONPYCACHEPREFIX=/var/cache/pycache
    volumes:
      - ./:/code
    depends_on:
      - db
      - redis

  db:
    image: postgres:17
    networks:
      - avto_cargo
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pd_data:/var/lib/postgresql/data
  
  redis:
    networks:
      - avto_cargo
    image: redis
    ports:
      - "6380:6379"