# Generated by Django 5.2 on 2025-08-26 14:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Yetkazilmoqda', 'Yetkazilmoqda'), ('Olingan', 'Olingan'), ('Kutilmoqda', 'Kutilmoqda'), ('Yetkazib berilgan', 'Yetkazib berilgan')], max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('total_price', models.PositiveBigIntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'buyurtmalar',
            },
        ),
    ]
