# Generated by Django 5.2 on 2025-08-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_location_en_order_location_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
