# Generated by Django 5.2 on 2025-08-27 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_country'),
        ('orders', '0003_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_from', to='common.country'),
        ),
        migrations.AddField(
            model_name='order',
            name='location_from_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_from', to='common.country'),
        ),
        migrations.AddField(
            model_name='order',
            name='location_from_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_from', to='common.country'),
        ),
        migrations.AddField(
            model_name='order',
            name='location_from_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_from', to='common.country'),
        ),
        migrations.AddField(
            model_name='order',
            name='location_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_to', to='common.country'),
        ),
        migrations.AddField(
            model_name='order',
            name='location_to_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_to', to='common.country'),
        ),
        migrations.AddField(
            model_name='order',
            name='location_to_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_to', to='common.country'),
        ),
        migrations.AddField(
            model_name='order',
            name='location_to_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_to', to='common.country'),
        ),
    ]
