# Generated by Django 5.2 on 2025-08-26 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteConfir',
            new_name='SiteConfig',
        ),
    ]
