# Generated by Django 5.2 on 2025-08-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_siteconfir_siteconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Xizmatlar', 'verbose_name_plural': 'Xizmatlarimiz'},
        ),
    ]
