# Generated by Django 5.2 on 2025-09-03 18:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_banner_text_banner_text_en_banner_text_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisite',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('company_name', models.CharField(max_length=200)),
                ('legal_address', models.CharField(max_length=200)),
                ('tin', models.CharField(max_length=15)),
                ('okpo', models.CharField(max_length=10)),
                ('oked', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=200)),
                ('bank_code', models.CharField(max_length=15)),
                ('uzs', models.PositiveBigIntegerField()),
                ('usd', models.PositiveBigIntegerField()),
            ],
            options={
                'verbose_name': 'korxona rekvizit',
                'verbose_name_plural': 'korxona rekvizitlar',
            },
        ),
    ]
