# Generated by Django 5.2 on 2025-09-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_requisite'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisite',
            name='company_name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requisite',
            name='company_name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requisite',
            name='company_name_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requisite',
            name='legal_address_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requisite',
            name='legal_address_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requisite',
            name='legal_address_uz',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
