# Generated by Django 5.2 on 2025-09-03 18:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_requisite_company_name_en_requisite_company_name_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('title_uz', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_ru', models.CharField(max_length=200, null=True)),
                ('text', models.TextField()),
                ('text_uz', models.TextField(null=True)),
                ('text_en', models.TextField(null=True)),
                ('text_ru', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Maxfiylik siyosati',
                'verbose_name_plural': 'Maxfiylik siyosati',
            },
        ),
    ]
