# Generated by Django 5.2 on 2025-09-04 16:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_privacypolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTerms',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Foydalanuvchi shartlari',
                'verbose_name_plural': 'Foydalanuvchi shartlari',
            },
        ),
    ]
