# Generated by Django 5.2 on 2025-09-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_userterms'),
    ]

    operations = [
        migrations.AddField(
            model_name='userterms',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userterms',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userterms',
            name='text_uz',
            field=models.TextField(null=True),
        ),
    ]
