# Generated by Django 5.2 on 2025-09-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_userterms_text_en_userterms_text_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='full_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='full_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='full_text',
            field=models.TextField(null=True),
        ),
    ]
