# Generated by Django 5.2 on 2025-09-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_aboutus_full_text_news_full_text_service_full_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='full_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='full_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='full_text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='full_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='full_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='full_text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='full_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='full_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='full_text_uz',
            field=models.TextField(null=True),
        ),
    ]
